# Set up password-less sudo by running visudo and adding this line to the end:
# %deploy        ALL=(ALL)       NOPASSWD: ALL
---
- hosts: devhosts
  vars:
  remote_user: deploy
  tasks:
  - name: Install zsh, git, curl
    apt: name=zsh,git,curl  state=latest  force=yes
    become: true
  - name: Create dummy .zshrc file
    file: name=~/.zshrc  state=touch
  - name: Change user shell to zsh
    user: name=deploy shell=/bin/zsh
    become: true
