---
- hosts: devhosts
  vars:
  remote_user: deploy

  roles:
    - role: rvm_io.rvm1-ruby
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: "/home/{{ ansible_ssh_user }}/.rvm"
      # Last Ruby will become the rvm default:
      rvm1_rubies:
        - 'jruby-9.0.5.0'
        - 'ruby-2.3.0'

  tasks:
  - name: Install Oh-My-Zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
